name: Go Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22.2'
      
    - name: Build
      run: |
        mkdir -p dist
        GOOS=linux GOARCH=amd64 go build -ldflags "-X main.version=${{ github.ref_name }}" -o "dist/go-static-linux64"
        GOOS=windows GOARCH=amd64 go build -ldflags "-X main.version=${{ github.ref_name }}" -o "dist/go-static-win64.exe"
        GOOS=darwin GOARCH=arm64 go build -ldflags "-X main.version=${{ github.ref_name }}" -o "dist/go-static-macos"
      
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        update: true
        files: |
          dist/go-static-linux64
          dist/go-static-win64.exe
          dist/go-static-macos
        token: ${{ secrets.GITHUB_TOKEN }}
